---
name: Publish
on:
  push:
    tags:
      - "v*"
env:
  ALIAS: aquasecurity
  REP: kube-hunter
jobs:
  pypi:
    name: Publish To PyPI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        shell: bash
        run: |
          pip install -U pip
          pip install -r hunting/arp_spoof_hunter/requirements.txt
    
      - name: Build Arp Spoof Hunter
        shell: bash
        run: |
          python -m pip install wheel
          cd hunting/arp_spoof_hunter
          pip install .

      - name: Build Dns Spoof Hunter
        shell: bash
        run: |
          python -m pip install wheel
          cd hunting/dns_spoof_hunter
          pip install .

      - name: Publish distribution package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: hunting/arp_spoof_hunter
      
      - name: Publish distribution package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: hunting/dns_spoof_hunter